services:
  truth-bot:
    container_name: "truth-bot"
    build: .
    tty: true
    env_file: production.env
    restart: always
    volumes:
      - ./db:/app/db
    environment:
      - DATABASE_PATH=/app/db/newsbot.db
    healthcheck:
      test: [ "CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/db/newsbot.db').execute('SELECT 1').fetchone()" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
